name: im_client
description: An IM client built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  crypto: ^3.0.6
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
